### ISSUE TITLE
Still not working under Bullseye

### ISSUE THREAD

**Issue by PvdGulik** [JanJaapKo/domoticz-GoodWeSEMS#16]
Hello, 

This very nice plugin is working perfectly under Buster, but not under Bullseye.
I know it's due the Phyton version. Does anybody got this working under Bullseye?
It works in Domoticz Beta version. But I would like to use in production.

Please help me with the right instructions how to adjust Phyton to the working version under Bullseye.

Thanks!

Pieter

**Comment by JanJaapKo** [comment]
Well it works fine for me in Bullseye under Domoticz Beta. What is the issue in latest stable? Which errors?

**Comment by PvdGulik** [comment]
That’s what I read, before I upgraded. But it was solved in latest beta…

Can be closed…

Thanks!
