### ISSUE TITLE
change api renewal interval 

### ISSUE THREAD

**Issue by RneeJ** [JanJaapKo/domoticz-GoodWeSEMS#27]
**Is your feature request related to a problem? Please describe.**
Absolutely no problem ! 
Thank you for the nice working interface from Goodwe to Domoticz !

**Describe the solution you'd like**
Now the shortest api renewal interval time is 30 seconds.
I use the Energy Dashboard and my P1 data are update every 1 second.
It would be very nice if the update time from Goodwe could be shorter ie 5 to 10 seconds or so

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
According to Goodwe documentation the api interface could be questioned 3600 times an hour.

Kind regards, bedankt Jan Jaap!
Rene

**Comment by JanJaapKo** [comment]
Tnx for the suggestion. I added 10 sec (as the internal clock of Domoticz has by default a 10 sec heartbeat it is somewhat more complicated to go lower). Available in version 4.0.2

Which documentation sais you can pull each second? Most webservers aren't too keen on being polled so often....

**Comment by RneeJ** [comment]
10 sec is ok, thankx. 
3600 calls max per hour : 

https://community.goodwe.com/solution/GOODWE%20API
Or : https://community.goodwe.com/static/images/2024-08-20597794.pdf

On page 2 just above table 2:

![image](https://github.com/user-attachments/assets/ffd240a6-95e4-421b-947f-8b04d104b27b)

You need a login via Sems portal.
