### ISSUE TITLE
Domoticz - GoodWe plug in not working

### ISSUE THREAD

**Issue by jan-sgn** [JanJaapKo/domoticz-GoodWeSEMS#6]
**Describe the bug**
JanJaapKo - installed your latest version of the GoodWe python plugin onto the latest Domoticz on RPI4B
RPI running raspbian 11 bullseye - yesterday installed
Setting up new hardware and devices is ok, can add the P1 data of my smart meter.
Adding the latest download clone into the plugins of the GoodWE SEMS python does not result in data
The hardware not seen and can not add devices - after restarting the domotica service and rebooting the RPI get a black screen with white narrow stripes vertical ...

**To Reproduce**

**Expected behavior**
I expected to be able to add the power output of my solar array

**Screenshots**
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/97793396/149624322-b629dccd-c727-4f61-82b1-0bf9269483a3.png">

**Domoticz environment (please complete the following information):**
 - Domoticz Version: can not see anymore, the server is down
 - Python Version: 3.9.2 on the RPI

**Additional context**

**Comment by JanJaapKo** [comment]
Hi @jan-sgn ,

Sorry for late response, don't get alerts from github....

Are you sure that:
- you are using the 'GoodWe solar inverter via SEMS API' plugin (and not 'GoodWe solar inverter via Web API')?
- did you restart Domoticz after cloning into domoticz/plugins directory? This is needed for Domoticz to see the new plugin
- any errors in the log?
- if not in the log window, then please check the logfile (normally in /tmp/)

**Comment by jan-sgn** [comment]
JanJaapKo - I checked the advise you gave (ref above) - all in good order, initial set up for Domoticz works ok, but when installing the plugin SEMS API (not the WebAPI) then the screen on Domoticz remains black, nothing visible. I worked a fair part of the afternoon to get to the bottom of this, and I read somewhere that the current Domoticz and GoodWe SEMS API do not work for the plugins under Raspi Bullseye --- OK, I blanked all out and reinstalled an image Raspi Buster -- and then when installing Domoticz with the SEMS API the screen is as expected with output on the screen --- don't know what is the issue, but definitely worth checking up on and fixing -- sorry, can not help with Python programming, not enough skills ... thanks, and good luck --- Jan

**Comment by JanJaapKo** [comment]
Ok, hope that using Raspian works out for you. Closing this issue
